#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 NetCalcKit contributors
"""Build the NetCalcKit standard list from independently reviewed domains."""

from __future__ import annotations

from pathlib import Path

from domain_utils import load_domains

ROOT = Path(__file__).resolve().parents[1]
CURATED = ROOT / "sources" / "curated.txt"
ALLOWLIST = ROOT / "allowlists" / "allowlist.txt"
OUTPUT = ROOT / "blocklists" / "standard.txt"
HEADER = (
    "# NetCalcKit Standard DNS Blocklist\n"
    "# SPDX-License-Identifier: ODbL-1.0\n"
    "# Copyright (c) 2026 NetCalcKit contributors\n"
    "# Attribution: https://github.com/muzii9/netcalckit-blocklist\n"
    "# Independently curated and generated by scripts/build.py.\n"
    "# Format: one lowercase domain per line.\n"
)


def main() -> None:
    try:
        allowlisted = set(load_domains(ALLOWLIST))
        curated = set(load_domains(CURATED))
    except ValueError as error:
        raise SystemExit(f"ERROR: {error}") from error

    domains = sorted(curated - allowlisted)

    body = "\n".join(domains)
    OUTPUT.write_text(HEADER + (body + "\n" if body else ""), encoding="utf-8")
    print(f"Wrote {len(domains)} domains to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
