#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 NetCalcKit contributors
"""Build generated NetCalcKit domain files from the structured rule database."""

from __future__ import annotations

from pathlib import Path

from domain_utils import load_domains
from rule_db import approved_domains, domains_for_tier, load_rules

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "rules" / "rules.csv"
ALLOWLIST = ROOT / "allowlists" / "allowlist.txt"
CURATED = ROOT / "sources" / "curated.txt"
STANDARD = ROOT / "blocklists" / "standard.txt"

CURATED_HEADER = (
    "# Independently reviewed NetCalcKit domains\n"
    "# SPDX-License-Identifier: ODbL-1.0\n"
    "# Copyright (c) 2026 NetCalcKit contributors\n"
    "# GENERATED from rules/rules.csv by scripts/build.py; do not edit by hand.\n"
    "# One lowercase domain per line.\n"
)
HEADER = (
    "# NetCalcKit Standard DNS Blocklist\n"
    "# SPDX-License-Identifier: ODbL-1.0\n"
    "# Copyright (c) 2026 NetCalcKit contributors\n"
    "# Attribution: https://github.com/muzii9/netcalckit-blocklist\n"
    "# Independently curated and generated by scripts/build.py.\n"
    "# Source of truth: rules/rules.csv\n"
    "# Format: one lowercase domain per line.\n"
)


def _write_domains(path: Path, header: str, domains: list[str]) -> None:
    body = "\n".join(domains)
    path.write_text(header + (body + "\n" if body else ""), encoding="utf-8")


def main() -> None:
    try:
        rules = load_rules(RULES)
        allowlisted = set(load_domains(ALLOWLIST))
    except ValueError as error:
        raise SystemExit(f"ERROR: {error}") from error

    curated = approved_domains(rules)
    standard = sorted(set(domains_for_tier(rules, "standard")) - allowlisted)

    _write_domains(CURATED, CURATED_HEADER, curated)
    _write_domains(STANDARD, HEADER, standard)

    print(f"Wrote {len(curated)} domains to {CURATED.relative_to(ROOT)}")
    print(f"Wrote {len(standard)} domains to {STANDARD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
