#!/usr/bin/env python3
"""Build the NetCalcKit standard DNS blocklist from approved sources."""

from __future__ import annotations

import ipaddress
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "sources" / "sources.txt"
ALLOWLIST = ROOT / "allowlists" / "allowlist.txt"
OUTPUT = ROOT / "blocklists" / "standard.txt"
HEADER = (
    "# NetCalcKit Standard DNS Blocklist\n"
    "# Generated by scripts/build.py; do not edit generated rules manually.\n"
    "# Format: one lowercase domain per line.\n"
)


def active_lines(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith(("#", "!", "["))
    ]


def normalize_domain(line: str) -> str | None:
    value = line.split("#", 1)[0].strip().lower().rstrip(".")
    parts = value.split()

    if len(parts) == 2 and parts[0] in {"0.0.0.0", "127.0.0.1"}:
        value = parts[1].rstrip(".")
    elif len(parts) != 1:
        return None

    if value == "localhost":
        return None

    try:
        ipaddress.ip_address(value)
        return None
    except ValueError:
        pass

    labels = value.split(".")
    if (
        len(value) > 253
        or len(labels) < 2
        or any(
            not label
            or len(label) > 63
            or label.startswith("-")
            or label.endswith("-")
            or not all(character.isalnum() or character == "-" for character in label)
            for label in labels
        )
    ):
        return None

    return value


def fetch(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "NetCalcKit-Blocklist/0.1"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def main() -> None:
    allowlisted = {
        domain
        for line in active_lines(ALLOWLIST)
        if (domain := normalize_domain(line))
    }
    domains: set[str] = set()

    for url in active_lines(SOURCES):
        parsed = urlparse(url)
        if parsed.scheme != "https" or not parsed.netloc:
            raise ValueError(f"Source must be a valid HTTPS URL: {url}")

        for line in fetch(url).splitlines():
            domain = normalize_domain(line)
            if domain and domain not in allowlisted:
                domains.add(domain)

    body = "\n".join(sorted(domains))
    OUTPUT.write_text(HEADER + (body + "\n" if body else ""), encoding="utf-8")
    print(f"Wrote {len(domains)} domains to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
